apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-task-platform
data:
  PORT: "5000"
  CORS_ORIGIN: "*"
  TASK_QUEUE_KEY: "ai_tasks_queue"
  MONGO_URI: "mongodb://mongo:27017/ai_task_platform"
  REDIS_URL: "redis://redis:6379"
