apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ai-task-platform
spec:
  replicas: 2
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: ujjwal12376/ai-task-frontend:latest
          ports: [{ containerPort: 8080 }]
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "150m", memory: "128Mi" }
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-task-platform
spec:
  selector: { app: frontend }
  ports:
    - port: 80
      targetPort: 8080
